1.1
SELECT COUNT(No_Of_Copies)
FROM BOOK_COPIES
WHERE (
	BookId IN (SELECT BookId FROM BOOK WHERE Title = 'The Lost Tribe')
	AND
	BranchId IN (SELECT BranchId FROM LIBRARY_BRANCH WHERE BranchName = 'Sharpstown')
)

1.2
SELECT COUNT(No_Of_Copies)
FROM BOOK_COPIES
WHERE BookId IN (SELECT BookId FROM BOOK WHERE Title = 'The Lost Tribe')
GROUP BY BranchId

1.3
SELECT Name 
FROM BORROWER B
WHERE NOT EXISTS ( SELECT * FROM BOOK_LOANS WHERE CardNo = B.CardNo )

1.4
SELECT Title, Name, Address
FROM BOOK_LOANS BL JOIN LIBRARY_BRANCH ON BranchId
	JOIN BORROWER ON CardNo
	JOIN BOOK ON BookId
WHERE GETDATE() = BL.DueDate AND BranchName = 'SharpsTown'

1.5
SELECT BranchName, COUNT(BookId)
FROM BOOK_LOANS RIGHT JOIN LIBRARY_BRANCH ON BranchId
GROUP BY BranchId, BranchName

1.6
SELECT Name, Address, COUNT(BookId, BranchId, CardNo)
FROM BOOK_LOANS LEFT JOIN BORROWER ON CardNo
GROUP BY CardNo
HAVING COUNT(BookId, BranchId, CardNo) > 5

1.7
SELECT Title, COUNT(No_of_Copies)
FROM BOOK_COPIES bc, LIBRARY_BRANCH lb, BOOK b, BOOK_AUTHORS ba
WHERE bc.BranchId = lb.BranchId AND bc.BookId = b.BookId AND ba.BookId = b.BookId AND b.AuthorName = 'Stephen King' 
AND lb.BranchName = 'Central'


2.1
SELECT DISTINCT FNAME, LNAME
FROM EMPLOYEE e, WORKS_ON w, PROJECT p
WHERE e.SSN = w.ESSN AND PNO = PNUMBER AND NDO = 5 AND PNAME = 'ProductX'
AND HOURS > 10

2.2
SELECT PNAME, PNUMBER, SUM(HOURS)
FROM PROJECT a, WORKS_ON b
WHERE b.PNO = a.PNUMBER
GROUP BY PNUMBER, PNAME
HAVING SUM(HOURS) > 10

2.3
SELECT DISTINCT idB 
FROM A as x
WHERE NOT EXISTS(
	SELECT idB
	FROM C c LEFT JOIN(
		SELECT *
		FROM A
		WHERE a.idB = x.idB
	) y ON c.idC = y.idC
	WHERE idB IS NULL
)

2.4 
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE SSN NOT IN (SELECT ESSN FROM WORKS_ON)

2.5
SELECT FNAME, LNAME, ADDRESS 
FROM EMPLOYEE e
WHERE SSN IN (SELECT ESSN FROM WORKS_ON wo, PROJECT p WHERE wo.PNO = p.PNUMBER AND PLOCATION = 'Houston')
AND DNO NOT IN (SELECT DNUMBER FROM DEPARTMENT a, DEPT_LOCATIONS b WHERE a.DNUMBER = b.DNUMBER AND DLOCATION = 'Houston')

2.6 -> sai vì chưa thỏa mãn là manager
SELECT LNAME 
FROM EMPLOYEE e LEFT JOIN DEPENDENT d ON d.ESSN = e.SSN
WHERE d.ESSN IS NULL

2.7
SELECT * 
FROM EMPLOYEE 
WHERE SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEE
)
ORDER BY SALARY DESC

2.8
SELECT *
FROM EMPLOYEE e
WHERE SALARY > (
	SELECT AVG(SALARY)
	FROM EMPLOYEE
	WHERE DNO = e.DNO
)
ORDER BY SALARY
